export const EmployeeListDataActionConst = {
  GET_EMPLOYEE_LIST_RED: 'GET_EMPLOYEE_LIST',
  GET_EMPLOYEE_LIST_SUCC: 'GET_EMPLOYEE_LIST_SUCC',
  GET_EMPLOYEE_LIST_FAIL: 'GET_EMPLOYEE_LIST_FAIL',
};

export const PendingShiftPostToServerActionConst = {
  PENDING_SHIFT_POST_REQ: 'PENDING_SHIFT_POST_REQ',
  PENDING_SHIFT_POST_SUCC: 'PENDING_SHIFT_POST_SUCC',
  PENDING_SHIFT_POST_FAIL: 'PENDING_SHIFT_POST_FAIL',
};
